version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "pql"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54320:5432"
